spring.application.name=Dyplom_DSS

spring.datasource.url=jdbc:mysql://localhost:3306/dss_db
spring.datasource.username=root
spring.datasource.password=121212

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view = true

jwt.secret=ak38dsk82j2l3jd912hd91j2nd1938dhs8d1hdh128dh1dh91ndh182dh
jwt.expiration=86400000  

